apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-magic-deployment
  labels:
    app: movie-magic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-magic
  template:
    metadata:
      labels:
        app: movie-magic
    spec:
      containers:
      - name: movie-magic
        image: nareshbhatia/movie-magic-shadcn:1.0.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-magic-service
spec:
  type: NodePort
  selector:
    app: movie-magic
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
